import socket
from tpm_security import *
from security import AES_key_gen


KEYFILE_OWN = "keyblob.bin"   # RSA file generated by the keygen function
KEYFILE_OTHER = "keyblob_2.bin" # RSA file recieved from the other gateway

DEFAULT_SOCKET_RECIEVE_SIZE = 2048
SOCKET_RECIEVE_INT_SIZE = 4


# Exchange keys between the two devices
# returns host key and size as well as peer key and size
def RSA_public_key_exchange(gateway_socket : socket.socket):
    # get IP addresses of devices
    source_address = gateway_socket.getsockname()[0]
    dest_address = gateway_socket.getpeername()[0]

    # key exchange with buffer
    # generate RSA key pair
    (rc, key_pub_buffer, key_pub_buffer_size) = RSA_key_gen(KEYFILE_OWN)
    if(rc != None):     # Success
        # transfer the keys between gateways
        if(source_address <= dest_address):  # source sends the key firsts
            # source sends its key to dest
            gateway_socket.send(key_pub_buffer_size.to_bytes(SOCKET_RECIEVE_INT_SIZE, 'big'))
            gateway_socket.send(key_pub_buffer)
            # then recieves the other key from dest
            peer_key_pub_buffer_size_bytes = gateway_socket.recv(SOCKET_RECIEVE_INT_SIZE)
            peer_key_pub_buffer_size = int.from_bytes(peer_key_pub_buffer_size_bytes, 'big')
            peer_key_pub_buffer = gateway_socket.recv(peer_key_pub_buffer_size)
        else:   # dest sends the key first
            # source recieves the key from dest
            peer_key_pub_buffer_size_bytes = gateway_socket.recv(SOCKET_RECIEVE_INT_SIZE)
            peer_key_pub_buffer_size = int.from_bytes(peer_key_pub_buffer_size_bytes, 'big')
            peer_key_pub_buffer = gateway_socket.recv(peer_key_pub_buffer_size)
            # then sends its key to dest
            gateway_socket.send(key_pub_buffer_size.to_bytes(SOCKET_RECIEVE_INT_SIZE, 'big'))
            gateway_socket.send(key_pub_buffer)

        return (key_pub_buffer, key_pub_buffer_size, peer_key_pub_buffer, peer_key_pub_buffer_size)
    else:
        print("*** Host device unable to generate RSA key")
        return None

    # key exchange with file
    # generate RSA key pair
    # rc = RSA_key_gen(KEYFILE_1)
    # if(rc != None):    # Success
    #     # transfer the keys between gateways
    #     if(source_address <= dest_address):  # source sends the key firsts
    #         # source sends its key to dest
    #         r_file = open(KEYFILE_1, "rb")
    #         data = r_file.read(1024)
    #         while data:
    #             gateway_socket.send(data)
    #             data = r_file.read(1024)
    #         r_file.close()

    #         # then recieves the other key from dest
    #         w_file = open(KEYFILE_2, "wb")
    #         data = gateway_socket.recv(1024)
    #         while data:
    #             w_file.write(data)
    #             data = gateway_socket.recv(1024)
    #         w_file.close()
    #     else:   # dest sends the key first
    #         # source recieves the key from dest
    #         w_file = open(KEYFILE_2, "wb")
    #         data = gateway_socket.recv(1024)
    #         while data:
    #             w_file.write(data)
    #             data = gateway_socket.recv(1024)
    #         w_file.close()

    #         # then sends its key to dest
    #         r_file = open(KEYFILE_1, "rb")
    #         data = r_file.read(1024)
    #         while data:
    #             gateway_socket.send(data)
    #             data = r_file.read(1024)
    #         r_file.close()


def random_number_exchange(gateway_socket : socket.socket):
    RNG_ERROR_CODE = b'00000000'

    RANDOM_NUM_SIZE = 4

    # get IP addresses of devices
    source_address = gateway_socket.getsockname()[0]
    dest_address = gateway_socket.getpeername()[0]

    # use RNG to determine who generates the key generated with TPM
    random_num_source = get_random(RANDOM_NUM_SIZE)
    if(random_num_source == None):  # if RNG failed set RNG_ERROR_CODE
        random_num_source = RNG_ERROR_CODE

    if(source_address <= dest_address):     # source sends the number first
        gateway_socket.send(random_num_source)
        random_num_dest = gateway_socket.recv(RANDOM_NUM_SIZE)
    else:                                   # dest sends the number first
        random_num_dest = gateway_socket.recv(RANDOM_NUM_SIZE)
        gateway_socket.send(random_num_source)

    return (random_num_source, random_num_dest)


def symmetric_key_exchange(gateway_socket : socket.socket, peer_RSA_public_key, peer_RSA_public_key_size):
    RNG_ERROR_CODE = b'00000000'

    # get IP addresses of devices
    source_address = gateway_socket.getsockname()[0]
    dest_address = gateway_socket.getpeername()[0]

    # exchange random numbers
    (random_num_source, random_num_dest) = random_number_exchange(gateway_socket)

    if(random_num_source != RNG_ERROR_CODE and random_num_dest != RNG_ERROR_CODE):  # Very fine random numbers, on both sides!
        if(random_num_source == RNG_ERROR_CODE):
            print("*** Host unable to generate random number using TPM")
        elif(random_num_dest == RNG_ERROR_CODE):
            print("*** Peer unable to generate random number using TPM")

        if(bytes_to_string(random_num_source) <= bytes_to_string(random_num_dest)):     # source generates the key
            # generate symmetric key
            result = AES_key_gen()

            if(result != None):     # encrypt symmetric key with RSA
                (sym_key, sym_key_size) = result
                result = RSA_encrypt(peer_RSA_public_key, peer_RSA_public_key_size, sym_key, sym_key_size)

                if(result != None): # send encrypted symmetric key
                    (sym_key_enc, sym_key_enc_size) = result
                    gateway_socket.send(sym_key_enc_size.to_bytes(SOCKET_RECIEVE_INT_SIZE, 'big'))
                    gateway_socket.send(sym_key_enc)
                else:
                    print("*** Host unable to perform RSA encryption with TPM")
                    return None
            else:
                print("*** Host unable to generate AES key")
                return None

        else:   # source recieves the key
            # recieve encrypted symmetric key
            sym_key_enc_size_bytes = gateway_socket.recv(SOCKET_RECIEVE_INT_SIZE)
            sym_key_enc_size = int.from_bytes(sym_key_enc_size_bytes, 'big')
            sym_key_enc = gateway_socket.recv(sym_key_enc_size)

            # decrypt symmetric key with RSA
            result = RSA_decrypt(KEYFILE_OWN, sym_key_enc, sym_key_enc_size)
            if(result != None):
                (sym_key, sym_key_size) = result
            else:
                print("*** Host unable to perform RSA decryption with TPM")
                return None


    else:   # They rigged the RNGs, they're trying to destroy our program! | --> use backup with smaller ip address
        print("** Using backup exchange procedure (IP address comparison)")

        if(source_address <= dest_address):     # source generates the key
            # generate symmetric key here
            result = AES_key_gen()

            if(result != None):     # encrypt symmetric key with RSA
                (sym_key, sym_key_size) = result
                result = RSA_encrypt(peer_RSA_public_key, peer_RSA_public_key_size, sym_key, sym_key_size)

                if(result != None): # send encrypted symmetric key
                    (sym_key_enc, sym_key_enc_size) = result
                    gateway_socket.send(sym_key_enc_size.to_bytes(SOCKET_RECIEVE_INT_SIZE, 'big'))
                    gateway_socket.send(sym_key_enc)
                else:
                    print("*** Host unable to perform RSA encryption with TPM")
                    return None
            else:
                print("*** Host unable to generate AES key")
                return None
        else:       # source recieves the key
            # recieve encrypted symmetric key
            sym_key_enc_size_bytes = gateway_socket.recv(SOCKET_RECIEVE_INT_SIZE)
            sym_key_enc_size = int.from_bytes(sym_key_enc_size_bytes, 'big')
            sym_key_enc = gateway_socket.recv(sym_key_enc_size)

            # decrypt symmetric key with RSA
            result = RSA_decrypt(KEYFILE_OWN, sym_key_enc, sym_key_enc_size)
            if(result != None):
                (sym_key, sym_key_size) = result
            else:
                print("*** Host unable to perform RSA decryption with TPM")
                return None

    return (sym_key, sym_key_size)


def key_exchange_routine(gateway_socket : socket.socket):
    result = RSA_public_key_exchange(gateway_socket)
    if(result != None):
        # (key_pub_buffer, key_pub_buffer_size, peer_key_pub_buffer, peer_key_pub_buffer_size)
        return symmetric_key_exchange(gateway_socket, result[2], result[3])
    else:
        return None
